name: Docker Image CI

on:
  push:
    branches: [ "main", feat/fixcicd ]
  pull_request:
    branches: [ "main", feat/fixcicd ]

jobs:
  test:
    name: Perform Lint test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        ls -al csvYaml/csvYaml/
        pylint ./csvYaml/csvYaml/*

  build:
    needs: test
    name: Build the Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
