name: Docker Image CI

on:
  push:
    branches: [ "main", feat/fixcicd ]
  pull_request:
    branches: [ "main", feat/fixcicd ]

jobs:
  test:
    name: Lint test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Linting Test
      run: |
        pylint ./csvYaml/csvYaml

  build:
    needs: test
    name: Build Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build Container
      run: |
        ls -al csvYaml
        version=`python3 csvYaml/fetchVersion.py`
        echo $version
        docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}
        docker build . --file Dockerfile --tag tricksterepo/csvyaml:"${version}"
        docker tag tricksterepo/csvyaml:"${version}" tricksterepo/csvyaml:latest
        docker push tricksterepo/csvyaml:"${version}" && docker push tricksterepo/csvyaml:latest

  imagetest:
    needs: build
    name: Perform Trivy and Dockle the Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Perform Trivy test
      run: |
        trivy image tricksterepo/csvyaml:latest
    - name: Perform Dockle test
      run: |
        dockle tricksterepo/csvyaml:latest

  deploy:
    needs: imagetest
    name: Deploy the Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker compose up -d


