name: Docker Image CI

on:
  push:
    branches: [ "main", feat/fixcicd ]
  pull_request:
    branches: [ "main", feat/fixcicd ]

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Perform Lint test
      run: pylint csvTaml/csvYaml


  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
