name: Docker Image CI

on:
  push:
    branches: [ "main", feat/fixcicd ]
  pull_request:
    branches: [ "main", feat/fixcicd ]

jobs:
  test:
    name: Perform Lint test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        pylint ./csvYaml/csvYaml

  build:
    needs: test
    name: Build the Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        ls -al csvYaml
        version=`python3 csvYaml/fetchVersion.py`
        echo $version
        echo "${pass} || ${env.pass} || ${{ secrets.DOCKER_PAT }} || ${password} "
        docker login -u ${{ vars.DOCKER_USERNAME }} -p ${password}
        docker build . --file Dockerfile --tag tricksterepo/csvyaml:"${version}"
        docker push tricksterepo/csvyaml:"${version}"
      env:
        password: "dckr_pat_luA7R4CDebgtA2HFVecPnsY_at0"
        pass: ${{ secrets.DOCKER_PAT }}

