name: Docker Image CI

on:
  push:
    branches: [ "main", feat/fixcicd ]
  pull_request:
    branches: [ "main", feat/fixcicd ]

jobs:
  test:
    name: Perform Lint test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        pylint ./csvYaml/csvYaml

  build:
    needs: test
    name: Build the Docker image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: |
        ls -al
        version='python3 csvYaml/fetchVersion.py'
        docker login --username ${{ env.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PAT }}
        docker build . --file Dockerfile --tag tricksterepo/csvyaml:"${version}"
        
